export const ROLES = {
  MASTER: "MASTER",
  TECNICO: "TECNICO",
  USUARIO: "USUARIO",
} as const;

export const STATUS = {
  NUEVO: "NUEVO",
  PENDIENTE_ASIGNACION: "PENDIENTE_ASIGNACION",
  ASIGNADO: "ASIGNADO",
  EN_PROCESO: "EN_PROCESO",
  ESPERA_USUARIO: "ESPERA_USUARIO",
  RESUELTO: "RESUELTO",
  CERRADO: "CERRADO",
  REABIERTO: "REABIERTO",
  CANCELADO: "CANCELADO",
} as const;

// Estados desde los que un ticket se considera "abierto" (activo)
export const OPEN_STATUSES: string[] = [
  STATUS.NUEVO,
  STATUS.PENDIENTE_ASIGNACION,
  STATUS.ASIGNADO,
  STATUS.EN_PROCESO,
  STATUS.ESPERA_USUARIO,
  STATUS.REABIERTO,
];

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export const NOTIFICATION_TYPES = {
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_REASSIGNED: "TICKET_REASSIGNED",
  COMMENT_ADDED: "COMMENT_ADDED",
  STATUS_CHANGED: "STATUS_CHANGED",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  TICKET_CLOSED: "TICKET_CLOSED",
  TICKET_REOPENED: "TICKET_REOPENED",
  TICKET_CANCELED: "TICKET_CANCELED",
  PASSWORD_RESET: "PASSWORD_RESET",
} as const;
